### ISSUE TITLE
ContractCreate returns ContractIsNotUnique error or old ID when it collides with a cancelled deployments

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/substrate-pallets#21]
Contract 580 was created with hash `f33942f87a8e3fcca5ca65b18e607b6a` (don't know why it appears in polka with a different hash). `ContractIDWithNodeIDAndHash(4, f33942f87a8e3fcca5ca65b18e607b6a)` returns 580 while using the hash in the contract details in polka returns 0. Creating a new contract with the same hash gives ContractIsNotUnique.

```go
identity, err := substrate.IdentityFromPhrase(string("words"))
if err != nil {
	panic(err)
}
sub, err := substrate.NewSubstrate(Substrate)
if err != nil {
	panic(err)
}
hash := []byte{0xf3, 0x39, 0x42, 0xf8, 0x7a, 0x8e, 0x3f, 0xcc, 0xa5, 0xca, 0x65, 0xb1, 0x8e, 0x60, 0x7b, 0x6a}
hashHex := hex.EncodeToString(hash)
fmt.Printf("[DEBUG] HASH: %s\n", hashHex)
contractID, err := sub.CreateContract(&identity, 4, nil, hashHex, 0)
if err != nil {
	panic(err)
}
```

And sometimes CreateContract returns id 580 and doesn't return an error. Which causes the deployment to fail with `object '580' exist: exists`.

**Comment by muhamadazmy** [comment]
May be the contract can be smart enough to re-set a canceled contract state to "Active" again an return the same id if the twin-id and hash are the same. (i assume the node id should also be part of this unique key)

**Comment by DylanVerstraete** [comment]
added in: https://github.com/threefoldtech/tfchain_pallets/commit/60512e2c401351f65418fc365e4d3250a8a22511
