### ISSUE TITLE
need a way to list my contracts

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/substrate-pallets#26]
i can't find a way to list my all contracts 
i tried from polka website and got unknown
![contract_issue](https://user-images.githubusercontent.com/31102305/133933738-b679cfb6-6f87-4cbf-ab8e-5de3581fed2b.png)

**Comment by xmonader** [comment]
moved to the right repo.

**Comment by DylanVerstraete** [comment]
You can list your contracts using the graphql:

example
```
query MyQuery {
  nodeContracts(where: {twinId_eq: 1}) {
    id
  }
}
```
