### ISSUE TITLE
Update a pricing policy should accept same name

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/substrate-pallets#42]
Currently when trying to update a pricing policy you cannot use the same name as the original one. We should allow this.

Also we should allow updating name contract values (check pricing policy create)

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/tfchain_pallets/pull/43#

**Comment by DylanVerstraete** [comment]
Live on devnet and testnet
