### ISSUE TITLE
Define pricing for TFChain testnet

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/substrate-pallets#46]
Based on https://github.com/threefoldtech/tf_operations/issues/336 , suggestion to revise the price on testnet.

How to define ? 1/10 of mainnet price, for all ? Or difference pricing per service ex. for IP addresses ?

**Comment by DylanVerstraete** [comment]
Set to 1/10 of pricing defined here https://library.threefold.me/info/threefold/#/tfgrid/grid/pricing

**Comment by DylanVerstraete** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.test.threefold.io#/explorer/query/0xfc7dd1137e91fa00b112ff91359dc79bc7e0250203413677948f22535641438b
