### ISSUE TITLE
The source and exact version from which pallet_staking was copied is not documented

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/substrate-pallets#54]
Without this information it is impossible to track changes and bug fixes to the original source and see if they need to be applied to our modified copy.

**Comment by DylanVerstraete** [comment]
It's V3 substrate, since all our dependencies are V3

**Comment by robvanmieghem** [comment]
Please just document the location and version in markdown

**Comment by DylanVerstraete** [comment]
added in https://github.com/threefoldtech/tfchain_pallets/commit/472af2ea74162d33f6394968e9f6b61b13298ced
