### ISSUE TITLE
pallet_staking dependencies question

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/substrate-pallets#55]
in the cargo.toml dev-dependencies resides `pallet-staking-reward-curve = { version = "3.0.0" }` Is this still relevant as it was called in inflation.rs in the test module and inflation.rs has been removed.
If it is no longer relevant, please remove it.

**Comment by DylanVerstraete** [comment]
removed in https://github.com/threefoldtech/tfchain_pallets/commit/0c7657b2d688f596f0de38e005019f2a9c3acf7f
