### ISSUE TITLE
New contracts billing reporting period is 75 mins

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/substrate-pallets#76]
env: devnet

old contracts were reporting every one hour
![image](https://user-images.githubusercontent.com/41957921/146188611-b6bd0c20-27d3-43a6-badd-4a849970db1c.png)

new contracts are reporting every 75 mins
![image](https://user-images.githubusercontent.com/41957921/146188765-37f42474-e476-4e9a-80bf-867c12756480.png)

### Expected 

All contracts should report every hour

**Comment by DylanVerstraete** [comment]
Okay, we investigated this issue and it seems like 1 out of 5 of our validators on devnet is down. Causing a 20% block delay at each interval. So this is not an issue with the code

**Comment by DylanVerstraete** [comment]
Should be fixed because we restored the validator that was down
