### ISSUE TITLE
supporting terms and conditions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/substrate-pallets#90]
There was a recent feature request to have in tfchain that the user agree to terms and conditions

typically should mean the following

1- the user agrees to a specific version so that version and the hash (or even the content they agreed on) needs to be tracked
2- there're concerns for the upgrades because that typically should be part of the DAO, it can't say `i agree always to the latest terms and conditions provided by threefold`
3- if there's a DAO request and new terms and conditions got pushed, how are we going to handle that approved terms across all extrinsics?
4- can it be as simple as in other websites (if you continue using this website, it means you agreed to the terms and conditions and specify the link)  without tracking that on the chain?

**Comment by despiegk** [comment]
we should just track

- who they are
- link they signed
- time they signed

thats good enough

we have 2

- generic T&C for everyone just using the portal
- farming T&C when they register their node

**Comment by DylanVerstraete** [comment]
I propose we also hash the document content client side and save the hash on chain
